defaults: &defaults
  working_directory: ~/hellomrsun.github.io
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.6
    environment:
      BUNDLE_PATH: ~/hellomrsun.github.io/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - hellomrsun.github.io-{{ checksum "Gemfile.lock" }}
            - hellomrsun.github.io-fallback
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: hellomrsun.github.io-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site